name = "v20251104"
main = "dist/_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true
pages_build_output_dir=""

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改

#id = ""				#KV数据库id



