name: Publish to Cloudflare
on:
  schedule:
    - cron: "0 18 * * *" # every day, UTC 18:00 is 2:00AM at China
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run a build step here if your project requires
      - name: Install dependencies
        run: npm install
      - name: Run build for uglifyjs
        run: npm run build
        
      - name: Publish to Cloudflare B
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ vars.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Change the working directory
          command: pages deploy ./dist --project-name=edge
        id: publish
      - name: Outputs of edge B
        run: |
          echo "ID: ${{ steps.publish.outputs.id }}"
          echo "URL: ${{ steps.publish.outputs.url }}"
          echo "Environment: ${{ steps.publish.outputs.environment }}"
          echo "Alias: ${{ steps.publish.outputs.alias }}"

      - name: Publish to Cloudflare C
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ vars.CLOUDFLARE_API_TOKEN_C }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID_C }}
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Change the working directory
          command: pages deploy ./dist --project-name=edge
        id: publishc
      - name: Outputs of edge C
        run: |          
          echo "ID: ${{ steps.publishc.outputs.id }}"
          echo "URL: ${{ steps.publishc.outputs.url }}"
          echo "Environment: ${{ steps.publishc.outputs.environment }}"
          echo "Alias: ${{ steps.publishc.outputs.alias }}"
